### ISSUE TITLE
README.md Link to "Top Global Hackathons" and "Competitions" are not working.

### ISSUE THREAD

**Issue by FanciestW** [dipakkr/A-to-Z-Resources-for-Students#1036]
When clicking on the links for "Top Global Hackathons" or "Competitions" under the "Hackathons and Events" section, the link doesn't jump to their respective sections.

**Comment by FanciestW** [comment]
May I fix this? I have started looking into solutions to this issue. Thanks!

**Comment by arthur322** [comment]
I can take care of this!

**Comment by FanciestW** [comment]
@arthur322 I found a fix and opened a PR for it. 
https://github.com/dipakkr/A-to-Z-Resources-for-Students/pull/1037
