### ISSUE TITLE
Make Developer club and meetup section more interactive 

### ISSUE THREAD

**Issue by dipakkr** [dipakkr/A-to-Z-Resources-for-Students#1085]
you can try adding a table with column s.no, title, type and location. 

send a patch fixing the same.

**Comment by Ishaan28malik** [comment]
i am going to work on this please assign this to me 
and also please specify what changes do u want .
@dipakkr

**Comment by dipakkr** [comment]
Fixed #1088 by @Ishaan28malik

**Comment by dipakkr** [comment]
> i am going to work on this please assign this to me
> and also please specify what changes do u want .
> @dipakkr

Its good !!
