### ISSUE TITLE
Link to Android section in README doesn't work

### ISSUE THREAD

**Issue by catielynncodes** [dipakkr/A-to-Z-Resources-for-Students#1090]
Clicking on "For Beginners 👶" under 1.4 Android Development takes you to a 404 Page Not Found.
This is the link attached to the text:
https://github.com/dipakkr/A-to-Z-Resources-for-Students/blob/master/Android.md

**Comment by dipakkr** [comment]
@catielynncodes thanks for pointing out !! You can send a patch fixing the same.

**Comment by dipakkr** [comment]
@catielynncodes after clicking on this link it should go to Android.md file in Android folder.

**Comment by dipakkr** [comment]
fixed !!
