### ISSUE TITLE
Make Contents under Docker heading more descriptive

### ISSUE THREAD

**Issue by co16353sidak** [dipakkr/A-to-Z-Resources-for-Students#1111]
Under the docker section, the contents could be more descriptive so as to make it easier for someone to read them and get a gist of what the link will be and where it will take them
also the links should contain the name of the page they will be visiting when they click the link.
The format followed under Javascript heading follows the right methodology.

Would like to open a PR for the same.

**Comment by dipakkr** [comment]
@co16353sidak sure go ahead and send a PR !

**Comment by co16353sidak** [comment]
Please review and comment.
