### ISSUE TITLE
Add Best Blog for Students

### ISSUE THREAD

**Issue by dipakkr** [dipakkr/A-to-Z-Resources-for-Students#1122]

**Comment by krishnakakade1999** [comment]
<P> both are useful for students to refer and learn content</b>
<b>freecodecamp.com</b>  
<br>
<b>medium.com</b>

**Comment by LeenaKaushik11** [comment]
Can I work on this issue?

**Comment by pahesali** [comment]
These are the best I know:
https://www.cursoemvideo.com (in this vpce learn new languages)

https://www.urionlinejudge.com.br/judge/en/login (in this you show what you know)

**Comment by cherryWood55** [comment]
Is the issue still open?

**Comment by ISHAGUPTA1286** [comment]
i will work on it

**Comment by dipakkr** [comment]
Sure you guys can work !

**Comment by snehit31** [comment]
How can we contribute?shall we make a file and add or else kindly tell us the alternative.
