### ISSUE TITLE
Fix broken link in the Student Benefits and Packs links collection

### ISSUE THREAD

**Issue by Niweera** [dipakkr/A-to-Z-Resources-for-Students#1129]
The link for [Free Web Hosting for 1 year | Znetlive](https://www.znetlive.com/student-web-hosting/) is not working. There are some reasons to belive that ZnetLive is not providing student web hosting services anymore. Please fix it.

**Comment by nitink4472** [comment]
I think the link is working properly.

**Comment by Niweera** [comment]
It was not working when I was checking it. Apparently now it is working. Thanks anyways...

**Comment by nitink4472** [comment]
But this issue should have been closed as it got fixed. I commented as i thought there may be any problem that still persists?

**Comment by Niweera** [comment]
> But this issue should have been closed as it got fixed. I commented as i thought there may be any problem that still persists?

No.issues.
