### ISSUE TITLE
Add Top 10 YouTube Channel for each category

### ISSUE THREAD

**Issue by dipakkr** [dipakkr/A-to-Z-Resources-for-Students#1137]
1. Technology

2. Startup

3. Design

4. Business 

5. Finance

Pls also mention the description of the channel and no. of subscribers

**Comment by zohaib304** [comment]
Here are some channels that I'm following 
**Technology**
- [freeCodeCamp.org ](https://www.youtube.com/channel/UC8butISFwT-Wl7EV0hUK0BQ) 1.28M subscribers
- [Traversy Media](https://www.youtube.com/channel/UC29ju8bIPH5as8OGnQzwJyA) 861K subscribers
- [Learn Engineering](https://www.youtube.com/channel/UCqZQJ4600a9wIfMPbYc60OQ) 2.89M subscribers
- [Coding Tech](https://www.youtube.com/channel/UCtxCXg-UvSnTKPOzLH4wJaQ) 482K subscribers
- [Physics Girl](https://www.youtube.com/channel/UC7DdEm33SyaTDtWYGO2CwdA) 1.37M subscribers

**Design**
- [Adobe Creative Cloud](https://www.youtube.com/channel/UCL0iAkpqV5YaIVG7xkDtS4Q) 653K subscribers
- [DesignCourse](https://www.youtube.com/channel/UCVyRiMvfUNMA1UPlDPzG5Ow) 439K subscribers
- [GFXMentor](https://www.youtube.com/channel/UCP3AIk974-PeB9bg1Mc7wug) 333K subscribers
- [Will Paterson](https://www.youtube.com/user/breakdesignsco) 351K subscribers

I will add more. 😊

**Comment by Anirudh257** [comment]
**Startup**

- [How to Start a Startup](https://www.youtube.com/channel/UCxIJaCMEptJjxmmQgGFsnCg) 100K subscribers
- [Time Ferris](https://www.youtube.com/user/masterlock77/featured) 485K subscribers
- [Naval Ravikant](https://www.youtube.com/channel/UCh_dVD10YuSghle8g6yjePg) 39.7K subscribers

**Comment by Tumo505** [comment]
Technology

- [Unbox Therapy](https://www.youtube.com/user/unboxtherapy) 15.5M subscribers
- [Linus Tech Tips](https://www.youtube.com/user/LinusTechTips) 9.25M subscribers
- [The Verge](https://www.youtube.com/user/TheVerge) 2.72M subscribers
- [Android Authority](https://www.youtube.com/user/AndroidAuthority) 3.33M subscribers
- [Techquickie](https://www.youtube.com/user/Techquickie) 3M subscribers
- [Tech Insider](https://www.youtube.com/channel/UCVLZmDKeT-mV4H3ToYXIFYg)
- [Jonathan Morrison](https://www.youtube.com/user/tldtoday) 2.66M subscribers
- [Future HD](https://www.youtube.com/channel/UCEdcgjfC2yZfRrX0Y2yW0hQ) 243K subscribers
- [Pro Hacker](https://www.youtube.com/channel/UC25pyzZn8f4l2jgy3IBV20A) 498K subscribers
[ Tech of Tomorrow](https://www.youtube.com/user/techtomorrow) 559K subscribers

**Comment by mariatheresahqs** [comment]
**Technology**

01. [Talks at Google](https://www.youtube.com/user/AtGoogleTalks) 1.04M subscribers
02. [Bloomberg Technology](https://www.youtube.com/channel/UCrM7B7SL_g1edFOnmj-SDKg)229K subscribers
03. [Wired](https://www.youtube.com/user/wired) 5.19M subscribers
04. [MIT Technology Review](https://www.youtube.com/user/TechnologyReview) 66.7K subscribers
05. [Google Developers ](https://www.youtube.com/user/GoogleDevelopers) 1.94M subscribers
06. [Women Techmakers](https://www.youtube.com/user/womentechmakers) 17.6K subscribers
07. [Google Cloud Platform](https://www.youtube.com/user/googlecloudplatform) 382K subscribers
08. [CS50](https://www.youtube.com/user/cs50tv) 335K subscribers
09. [Microsoft Developer](https://www.youtube.com/channel/UCsMica-v34Irf9KVTh6xx-g)135K subscribers
10. [Tech Insider](https://www.youtube.com/channel/UCVLZmDKeT-mV4H3ToYXIFYg) 2.77M subscribers

**Comment by tirthasheshpatel** [comment]
Seems like a nice idea!
Shall I start adding the links to the readme file?

**Comment by zohaib304** [comment]
@tirthasheshpatel surely.

**Comment by tirthasheshpatel** [comment]
The list is complete! Check the list in the README.md file of #1175
