### ISSUE TITLE
Add 5 Best Podcast in Each Category

### ISSUE THREAD

**Issue by dipakkr** [dipakkr/A-to-Z-Resources-for-Students#1138]
1. Technology

2. Startup and Entrepreneurship

3. Life

4. Other (if you found any good podcast which doesn't fall under the above category, please mention in this)

**Comment by KatSaldivar** [comment]
I'm sorry for all the notifications.  It's been a little while since I've contributed to a public repo and I'm out of practice. Please let me know if I did it wrong so I can fix it. 🙏
