### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by JoSchwartz** [dipakkr/A-to-Z-Resources-for-Students#1139]
"Learn and Understand NodeJS 💲 - Intermediate" and "What You Need To Know About Node.js" 
 both lead to non-existing links.

**Comment by dipakkr** [comment]
Thanks for reporting I will check it out and resolve soon !

**Comment by hamatimdotcom** [comment]
this issues should be closed

**Comment by JoSchwartz** [comment]
you are right
