### ISSUE TITLE
Documentation: serial number not in order in Contributors.md file

### ISSUE THREAD

**Issue by iamrajiv** [dipakkr/A-to-Z-Resources-for-Students#1141]
serial number not in order in `Contributors.md`  file like 326 and 348 is repeated also many times the order is broken or repeated

**Comment by whilson03** [comment]
I will work on it

**Comment by dipakkr** [comment]
@whilson03 go ahead !

**Comment by dev-wilson** [comment]
I have fixed it and created a PR
