### ISSUE TITLE
The first link in GSOC.md isn't working!!

### ISSUE THREAD

**Issue by arun664** [dipakkr/A-to-Z-Resources-for-Students#1181]
The first link in gsoc.md file is being redirected to Error Page (404) Not found.
Please fix this!!

Line : #29 
Link on how to prepare for gsoc.
Thank you

**Comment by dipakkr** [comment]
Feel to free to work on the issue thanks !

**Comment by Lawrence4code** [comment]
I'd like work on this, please.

**Comment by rikowars** [comment]
what is the link to the desired video?

**Comment by prabalgupta12** [comment]
i think i fixed the issue with a link you [ link](https://www.youtube.com/watch?v=u0IPiGhpwRE&t=14s)

**Comment by grh72573** [comment]
sharing
