### ISSUE TITLE
Add more Scholarships

### ISSUE THREAD

**Issue by cherryWood55** [dipakkr/A-to-Z-Resources-for-Students#1184]
I think there are more entries that could be added to this section. Take for instance, the following programs:

- https://research.adobe.com/adobe-india-women-in-technology-scholarship/

- https://www.iie.org/Programs/WeTech/STEM-Scholarships-for-Women/Goldman-Sachs-Scholarship
and some more..

**Comment by dipakkr** [comment]
@

**Comment by dipakkr** [comment]
@cherryWood55 you can send a PR adding the same.

**Comment by cherryWood55** [comment]
I'll do it by tomorrow, Deepak.
