### ISSUE TITLE
Add more international internship programs

### ISSUE THREAD

**Issue by iadeelzafar** [dipakkr/A-to-Z-Resources-for-Students#1256]
Please add more international internship programs like the Cisco one.

**Comment by yozaam** [comment]
I've added the 3 most reputed international internships to my PR

**Comment by yozaam** [comment]
Can we close this?

**Comment by iadeelzafar** [comment]
@yozaam Yeah.

**Comment by Ishaan28malik** [comment]
I have merged it @iadeelzafar @yozaam thanks for the contribution happy hacking.
