### ISSUE TITLE
udacity 404 not found

### ISSUE THREAD

**Issue by taran9873** [dipakkr/A-to-Z-Resources-for-Students#1322]
https://github.com/dipakkr/A-to-Z-Resources-for-Students/blob/master/ML/ML.md#11-where-to-start-in-ml

"Into to ML" redirects to udacity 404 not found page

**Comment by HeinKhantZaw** [comment]
Hi @taran9873, I've updated the link that you mentioned.

**Comment by taran9873** [comment]
thanks
