### ISSUE TITLE
Many links are broken. 

### ISSUE THREAD

**Issue by Nanak360** [dipakkr/A-to-Z-Resources-for-Students#1333]
I can work on the links if somebody assigns me to do so.

**Comment by HeinKhantZaw** [comment]
Some users updated a couple of broken links but the repo owner didn't merge. So, u can find the updated links in closed PRs.

**Comment by dipakkr** [comment]
hey @Nanak360  you can go ahead the fix those. 

@HeinKhantZaw  during hacktoberfest I got a lot of spam PR just,  I might have missed a few in closing those.

**Comment by siAyush** [comment]
Now, most of the links are fixed.
