### ISSUE TITLE
Want to Upload a Project

### ISSUE THREAD

**Issue by altaliya** [dipakkr/A-to-Z-Resources-for-Students#1347]
hello folks, I want to upload the coding of my Android App that I have created last month. Too Simple and best App, this is [web ](HTTP://www.packageslab.com/)View of my Site.

Reason of Share Regarding SEO.

I want to share this App coding then I suggest my colleague download the source code and edit it according to their SITE.

**Comment by siAyush** [comment]
Hey, you can create a repo in your account and push the code.
