### ISSUE TITLE
The Front-end Roadmap link is broken.

### ISSUE THREAD

**Issue by SugatoBagchi** [dipakkr/A-to-Z-Resources-for-Students#1350]
The frontend roadmap link is broken as shown below - 
<img width="812" alt="Screenshot 2021-03-14 161442" src="https://user-images.githubusercontent.com/68023376/111065552-6a8b8000-84e0-11eb-9a2c-41a86bae5401.png">

**Comment by dipakkr** [comment]
@SugatoBagchi thanks for fixing
