### ISSUE TITLE
Suggestion for other departmental resources

### ISSUE THREAD

**Issue by adimehta03** [dipakkr/A-to-Z-Resources-for-Students#1358]
Since there are resources added related to startups, finance and business, do you think it's a good idea to add other departmental resources as well?

**Comment by siAyush** [comment]
That's a good idea to create a separate department.

**Comment by adimehta03** [comment]
Awesome, I'll start working on a couple of departments and make a PR!

**Comment by siAyush** [comment]
Sure.
