### ISSUE TITLE
Suggestion to add API Setu 

### ISSUE THREAD

**Issue by adimehta03** [dipakkr/A-to-Z-Resources-for-Students#1360]
Suggestion to add https://apisetu.gov.in/.

It can be used for retrieving DL, RC, X and XII Marksheet, Ration Card, Income Certificate, Caste Certificate, CoWIN Vaccine Appointment details and much more.

**Comment by jagwsing** [comment]
I tried to get available vaccine by district but getting unauthorised access error.

**Comment by siAyush** [comment]
hey, @adimehta03  thanks for this suggestion but I don't this repo is a good fit you can look here https://github.com/public-apis/public-apis .

**Comment by adimehta03** [comment]
Awesome thanks!
