### ISSUE TITLE
 Broken link in README.md

### ISSUE THREAD

**Issue by kn-neelalohitha** [dipakkr/A-to-Z-Resources-for-Students#143]
## What happened?
I was going through [README.md](https://github.com/dipakkr/A-to-Z-Resources-for-Students/blob/master/README.md) as I was interested to contribute to this repository and learn about hackathons. When I clicked on "Hackathon Search Portal" under "2.Hackathons and Events" sections it  remained in the same page.
This is also the case when I clicked on "Startup Summits and Competitions" under the same section.
## What you expect to happen?
I expected to be taken to "Hackathon Search Portal" and "Startup Summits and Competitions"
## Reference: 
In [README.md](https://github.com/dipakkr/A-to-Z-Resources-for-Students/blob/master/README.md) under "**Table of Contents**" go to "**2.Hackathons and Events**" and click on"**Hackathon Search Portal**" and "**Startup Summits and Competitions**"

**Comment by dipakkr** [comment]
@kn-neelalohitha thanks for your interest. 

Sure, please go ahead and send a PR for the fix.

**Comment by kn-neelalohitha** [comment]
Sure! Thank you!

**Comment by kn-neelalohitha** [comment]
@dipakkr Raised PR [#144](https://github.com/dipakkr/A-to-Z-Resources-for-Students/pull/144)

**Comment by dipakkr** [comment]
@kn-neelalohitha thanks !! Please checkout other issues if you are interested to contributing !! Give a Star or Share if you liked our initiative.

**Comment by kn-neelalohitha** [comment]
Definitely!!

**Comment by kn-neelalohitha** [comment]
Issue fix : PR [#114](https://github.com/dipakkr/A-to-Z-Resources-for-Students/pull/144)
