### ISSUE TITLE
Add Translation in your Language

### ISSUE THREAD

**Issue by dipakkr** [dipakkr/A-to-Z-Resources-for-Students#150]

**Comment by dharmadev108** [comment]
Would it be useful if i translated the README into Italian?

**Comment by dipakkr** [comment]
@dharmadev108 yeah sure go ahead.

**Comment by kayrabCebll** [comment]
I will translate README.md to Turkish then?

**Comment by dipakkr** [comment]
@kayrabCebll go ahead !! Send a PR when you are done.

**Comment by NicoBelob** [comment]
I would like to add a German translation of the README

**Comment by dipakkr** [comment]
@NicoBelob you are welcome !! Please go ahead and send a patch

**Comment by AzogBiceps** [comment]
I'm translating the README doc in French!

**Comment by ghassemiN** [comment]
I'm translating the README doc in Persian!

**Comment by ghassemiN** [comment]
I would like to add a Persian translation of the README

**Comment by ghassemiN** [comment]
I would like to add a Persian translation of the README

**Comment by ghassemiN** [comment]
I would like to add a Persian translation of the README

**Comment by dipakkr** [comment]
@AzogBiceps Sure, please send a patch when done !!

**Comment by glasspinnA** [comment]
I'm translating the README into Swedish

**Comment by liliballe** [comment]
Hi. I'm interested in helping with the translation to Spanish (LatAm).
Any pointers on how to proceed will be welcome, I appreciate you help as this would be my first PR.

**Comment by dipakkr** [comment]
Hi @liliballe thanks for your interest. you can check the **translation** folder for available translation and how-to-contribute.md file to know steps how to do the first PR. Let me know if you face any difficulties.

**Comment by liliballe** [comment]
Hi there, I was wondering if I's get a hacktoberfest shirt with this minor challenge.
