### ISSUE TITLE
TRANSLATE : Add translation in Chinese 

### ISSUE THREAD

**Issue by dipakkr** [dipakkr/A-to-Z-Resources-for-Students#180]
Anyone willing to translate this Repo into Chinese language. Please contact. 

- I will make you colloaborater in this project so that you can have direct Push access. 

- Add Resources helpful for Chinese Users

**Comment by jiazheng0609** [comment]
I'm a native Chinese speaker and a student in Taiwan, I can help!

**Comment by dipakkr** [comment]
@jiazheng0609 sure please go ahead and send a pull request.

**Comment by dipakkr** [comment]
Are you taking this @jiazheng0609 ?

**Comment by jiazheng0609** [comment]
Yes, I will work on this.

**Comment by dipakkr** [comment]
@jiazheng0609 any updates ??
