### ISSUE TITLE
DESIGN : Update README front image. 

### ISSUE THREAD

**Issue by dipakkr** [dipakkr/A-to-Z-Resources-for-Students#186]
- Prefer to use Free Images or Create your own.
- Don't use Copyrighted Material.

**Comment by AaronCGoidel** [comment]
Created new design for front image and added it to README in #189

**Comment by dipakkr** [comment]
@AaronCGoidel thanks !! But, It doesn't look creative. I am looking for a replacement and better than the current one.

**Comment by dipakkr** [comment]
We are looking for new and creative design for README.md header image
