### ISSUE TITLE
TRANSLATION : Translate README.md in Portuguese 

### ISSUE THREAD

**Issue by dipakkr** [dipakkr/A-to-Z-Resources-for-Students#192]
- Check out the translation folder
- Find the README-pt-br.md
- Translate into the Portuguese Language. 

It is not mandatory to translate the whole page, just pick any section and do it.

**Comment by milaaraujo** [comment]
Hey @dipakkr! I opened PR #199. Tomorrow I can finish the translation.

**Comment by dipakkr** [comment]
@milaaraujo Great job !! Appreciate your contribution.

**Comment by milaaraujo** [comment]
I finished the translation with #225.

**Comment by dipakkr** [comment]
Okay, so should i close this issue ?  @milaaraujo

**Comment by vncsalencar** [comment]
Hey there, @dipakkr and @milaaraujo. Take a look at #227. Thanks!
