### ISSUE TITLE
HACKTOBERFEST : ADD your Introduction in Contributor list.

### ISSUE THREAD

**Issue by dipakkr** [dipakkr/A-to-Z-Resources-for-Students#194]
**Want to win a Hacktoberfest Tshirt ??** 

**Just Add your below details in **new-contributors.md** file and you are done.** 

- Name

- Introduction(what you do)

- Country or State

- Links of your social profile 

**- Prefer giving link to LinkedIn Profile. ( Networking :smiley: )**

 Don't forget to give a :star: if you like the content.

**Comment by albanmahmut** [comment]
Sounds good. :)

**Comment by dipakkr** [comment]
Still open for contribution.
