### ISSUE TITLE
Add MUG meetups to 2.5

### ISSUE THREAD

**Issue by Parikshit-Hooda** [dipakkr/A-to-Z-Resources-for-Students#21]

**Comment by Parikshit-Hooda** [comment]
MUG- MongoDB User Group. I will open PRs to my opened issues and later close them. Tag them hacktoberfest as they come.

**Comment by dipakkr** [comment]
@Parikshit-Hooda any updates ??

**Comment by Parikshit-Hooda** [comment]
I have opened PRs. I made all the commits and opened PRs individually,, so i think they are counted as 1 PR?

**Comment by dipakkr** [comment]
#45 by @Parikshit-Hooda

**Comment by dipakkr** [comment]
> I have opened PRs. I made all the commits and opened PRs individually,, so i think they are counted as 1 PR?

yes, it will be counted as 1 PR
