### ISSUE TITLE
SCHOLARSHIP : Add Scholarship Programs for Students 

### ISSUE THREAD

**Issue by dipakkr** [dipakkr/A-to-Z-Resources-for-Students#210]

**Comment by helloart3mis** [comment]
I'd like to contribute, but don't fully understand what needs to be done.  Little more specific please :)

**Comment by dipakkr** [comment]
Hi, @helloart3mis thanks for your interest.

You can check out the other scholarship programs which are already added here : 

[Check this Link](https://github.com/dipakkr/A-to-Z-Resources-for-Students#scholarships-runner)

With Scholarship Program, what I want to say is say there are various opportunities for student across the globe like some fellowship program in research or development (some are paid, some provide scholarship). or some benefit pack or discount which companies provide only for college students.

I hope you get it. Check the above link and [this section for more such samples](https://github.com/dipakkr/A-to-Z-Resources-for-Students#3-student-benefits-and-programs-fire).
