### ISSUE TITLE
CHEATSHEET : Make DBMS CheatSheet 

### ISSUE THREAD

**Issue by dipakkr** [dipakkr/A-to-Z-Resources-for-Students#286]
please check this page for reference  - 

https://github.com/dipakkr/A-to-Z-Resources-for-Students/blob/master/CheatSheet.md

**Comment by Anne97** [comment]
Is it still open? Can I take this up? 
Also the given link gives `404` error.

**Comment by dipakkr** [comment]
@Anne97 yes, it is still open. You can work on this.
