### ISSUE TITLE
HELP : Looking for Interested Backend and Frontend Developer to convert this repository resources into a Web App.  

### ISSUE THREAD

**Issue by dipakkr** [dipakkr/A-to-Z-Resources-for-Students#321]
The Students which are not from TIER 1 colleges doesn't have a good ecosystem(tech) in their college. But, There are lots of opportunities for these students apart from the academics like involvement in developer communities, hackathons, conference, Internship, startup conclaves, student exchange programs, Campus ambassador programs, open source communities and many more.

But due to lack of awareness, many students fail to grab these opportunities. Like I did.

**That is why We decided to compile a list of all the resources for students as well as working professional to do things what they love to do.**

In a Month, people over all over the world have contributed lots of resources, and we will have more and more resources everyday.

**That's is why We are building a web application for these resources to improve and personalize user experience where you can save and manage your faviourites resources.**

**We are Looking for Interested Frontend and Backend Developers to volunteer in the Project.**

If you are interested, please comment below. 

@Contrevien

**Comment by jhia** [comment]
:octocat:

**Comment by dipakkr** [comment]
hi, @jhia thanks for your interest. I have sent you a slack grp invite to your mail id (listed on Github). If interested, accept the invite so that we can discuss further. Thanks !!

**Comment by LindaKadz** [comment]
Interested!

**Comment by dipakkr** [comment]
> Interested!

Can you provide me your email id or mail me at : **deepakcse101@gmail.com**, so that I can send you the invite link.

**Comment by Aditya-Kolla** [comment]
Interested.

**Comment by Aditya-Kolla** [comment]
> > Interested.
> 
> thank you for interest @Aditya-Kolla. do you work on frontend or backend?

Nodejs Backend.

**Comment by dipakkr** [comment]
@Aditya-Kolla please mail me at deepakcse101@gmail.com. I will forward you the invite link.

**Comment by dipakkr** [comment]
> i'm Interested!, i prefer the backend to the frontend but is not a problem :)

please mail me at deepakcse101@gmail.com. I will forward you the invite link.

**Comment by schandan696** [comment]
Intrested

**Comment by dipakkr** [comment]
> I am also interested. Will send you an email for the invite link. Thanks ;)

sure :+1:

**Comment by HishamMubarak** [comment]
Hi, count me in. I am a full stack JavaScript developer working with React, Node and MongoDB. Send me an invitation at parengalhisham@gmail.com please.

**Comment by dipakkr** [comment]
**Anyone who is willing to contribute to Web app project can checkout -**
https://github.com/A2Z-hq

**Your contributions are welcome.** 

For more information, you can reach me out at - 

- Gmail - deepakcse101@gmail.com
-  LinkedIn - http://linkedin.in/in/dipakkr

**Comment by Roberasd** [comment]
I am really Interested! 

This is my email: rovalos@gmail.com

**Comment by nileshlaxmi** [comment]
Interested, working with React and Redux. Please let me know if I can contribute.

**Comment by Roberasd** [comment]
> > I am really Interested!
> > This is my email: [rovalos@gmail.com](mailto:rovalos@gmail.com)
> 
> what's your tech stack? you can check out the link below to view our projects. If you are comfortable working on the projects, let me know.
> 
> https://github.com/A2Z-hq



> > I am really Interested!
> > This is my email: [rovalos@gmail.com](mailto:rovalos@gmail.com)
> 
> what's your tech stack? you can check out the link below to view our projects. If you are comfortable working on the projects, let me know.
> 
> https://github.com/A2Z-hq

I sent you an email :)
