### ISSUE TITLE
Conference: Add JavaScript Conferences

### ISSUE THREAD

**Issue by Contrevien** [dipakkr/A-to-Z-Resources-for-Students#322]

**Comment by BalesabuGodugu** [comment]
@Contrevien please assign this issue on my name. I will add javascript conferences

**Comment by dipakkr** [comment]
hi @BalesabuGodugu Please go ahead and send your PR. I will merge it. 

As you are not the collaborator, Github repo has a feature only to assign collaborator for issue. So, officialy we can't.
