### ISSUE TITLE
HACKTOBERFEST: Add your details to the CONTRIBUTORS list

### ISSUE THREAD

**Issue by Contrevien** [dipakkr/A-to-Z-Resources-for-Students#328]
### Want to win a Hacktoberfest Tshirt ??

Just Add your below details in _CONTRIBUTORS.md_ file and you are done.

- Name

- Introduction(what you do)

- Country or State

- Links of your social profile

**Prefer giving link to LinkedIn Profile. ( Networking :smiley: )**

### Please Don't forget to give a :star: if you like the content.

**Comment by Ifyokoh** [comment]
Hello
In contributing to this repo, do you pull request for each content, or can you make all the changes for different content you have and pull request once?

**Comment by dipakkr** [comment]
> Hello
> In contributing to this repo, do you pull request for each content, or can you make all the changes for different content you have and pull request once?

No, Don't make large changes in a Pull Request. It becomes reliable and easier for us in a review, if you make particular changes in a pull request.
