### ISSUE TITLE
Add Summer and Winter internship programs offered by Universities around the world

### ISSUE THREAD

**Issue by Contrevien** [dipakkr/A-to-Z-Resources-for-Students#377]
Every year lots of Universities accept a student for **Summer and Winter Internship** across the world. But lots of students fails to grab these opportunities due to lack of awareness.

If you know about such programs, please add the link in the specified section in table of content on **README.md** page.

**Comment by hadesanirban** [comment]
i would like to solve this issue if you don't mind

**Comment by dipakkr** [comment]
@hadesanirban please go ahead.
