### ISSUE TITLE
Fix : Update the Type of Conferece in Section 8

### ISSUE THREAD

**Issue by dipakkr** [dipakkr/A-to-Z-Resources-for-Students#390]
**Your task -** 

- Research and find the type of conference and add in **Type** column.

**Possible Options** - 
**- ML**
**- JS**
**- Python**
**- Mobile** 
**- Web**
**- Security**

**Comment by HishamMubarak** [comment]
Added know types in PR #452

Some types are left to add, and some links are broken. Contribution guidelines say 'Do not remove anything', so might wanna do something about that.

**Comment by dipakkr** [comment]
@HishamMubarak great. Checkout #321 you might be interested !!
