### ISSUE TITLE
Add hackathon.com to 2.3

### ISSUE THREAD

**Issue by Parikshit-Hooda** [dipakkr/A-to-Z-Resources-for-Students#4]

**Comment by dipakkr** [comment]
Thanks @Parikshit-Hooda. I will add that or if you want you can send a PR.

**Comment by Parikshit-Hooda** [comment]
This is nice. I will send in a PR when hacktoberfest starts. I apologize for the late reply. I think this PR would count in the fest, right?

**Comment by Parikshit-Hooda** [comment]
merge the PRs.
