### ISSUE TITLE
Design : Design LOGO for A2Z 

### ISSUE THREAD

**Issue by dipakkr** [dipakkr/A-to-Z-Resources-for-Students#460]
add your samples in creative folder.

- put your username in place of filename and save it.

**Comment by lubacious** [comment]
Here is one possible logo:

![lubacious](https://user-images.githubusercontent.com/36712553/47477432-3621a700-d7f3-11e8-9ada-9d73595316f0.png)


I'm not sure how to connect this to a pull request. I am 100% new to the platform.

**Comment by dipakkr** [comment]
@lubacious I am sorry, but this logo is not good. However for making a PR, you can visit How-to-contribute.md file and check the steps.

**Comment by lubacious** [comment]
Is there anything in particular that I could do to improve it or change it?

Are there any elements missing from the logo that could be included?

**Comment by dipakkr** [comment]
@lubacious it should be creative. also, here Apple is not looking good.
