### ISSUE TITLE
HACKTOBERFEST : Accepting My First PR

### ISSUE THREAD

**Issue by dipakkr** [dipakkr/A-to-Z-Resources-for-Students#495]
**Are you a newbie, and willing to participate in open source and Hacktoberfest ?** 

Send you First PR. Do whatever you understand in the project. And send you First Pull Request. 

- You can fix any issue.
- You can add any content you want. 
- You can make new file.

**Let's take your first step toward open source. :smiley:** 

**Open for all**

**Comment by Edgarzerocool** [comment]
I add new contributor to CONTRIBUTORS.md but:
$ git push origin master
remote: Permission to dipakkr/A-to-Z-Resources-for-Students.git denied to Edgarzerocool.
fatal: unable to access 'https://github.com/dipakkr/A-to-Z-Resources-for-Students.git/': The requested URL returned error: 403

What happend?

**Comment by dipakkr** [comment]
@Edgarzerocool 

first fork this repository and then clone your forked version. If you directly clone my repository and push your changes to my repository, it will throw an error, as you don't have permission.

So, first fork this rep, then clone the forked version, make changes, push to your forked version and after that Click on Create Pull Request button.

**Comment by Edgarzerocool** [comment]
@dipakkr
OK thanks you, I send changes

**Comment by Contrevien** [comment]
Thank you for a splendid Hacktoberfest! :tada:
