### ISSUE TITLE
HACKTOBERFEST: Add your details to the CONTRIBUTORS list

### ISSUE THREAD

**Issue by dipakkr** [dipakkr/A-to-Z-Resources-for-Students#496]
### Want to win a Hacktoberfest Tshirt ??

Just Add your below details in _CONTRIBUTORS.md_ file and you are done.

- Name

- Introduction(what you do)

- Country or State

- Links of your social profile

**Prefer giving the link to LinkedIn Profile. ( Networking :smiley: )**

### Please Don't forget to give a :star: if you like the content.

**Comment by Edgarzerocool** [comment]
add contributor

**Comment by dipakkr** [comment]
@SamuelWoniowei create a PR

**Comment by JukieWalsh** [comment]
#746
