### ISSUE TITLE
Add projects for Full Stack Devs

### ISSUE THREAD

**Issue by dipakkr** [dipakkr/A-to-Z-Resources-for-Students#497]
This is an extension of #65

**If you have done, seen or known projects in the field of Full-stack Web Development which covers the basic + intermediate concepts and prove as a good base for beginners, adding that under the Full Stack Web Development section in the projects.md file.**

You need to add the Name and link to project source code

**Comment by dipakkr** [comment]
Yes @aashish-ak

**Comment by aashish-ak** [comment]
Hey @dipakkr , I added my MEAN STack project. See #512 , please have a look and merge as soon as possible.
Thanks
