### ISSUE TITLE
Make a Hacktoberfest Pull Request

### ISSUE THREAD

**Issue by dipakkr** [dipakkr/A-to-Z-Resources-for-Students#636]
With just 4 days left in Hacktoberfest Contest, We want to make sure everyone who visit our repository get a tshirt and laptop stickers from Github free of cost. 

**What you need to do ?**
- Make 5 pull request in any open source repository.

*"How you can do that** ? 
- Add any resources or You can add your name in Contributers.md file or checkout issue to solve them.

If you need any help, let us know In the comment section.

**Comment by Anne97** [comment]
Hi @dipakkr , I thought of adding a file for the internship program named `outreachy` when I saw a file for GSOC. Let me know if I can do that.

**Comment by dipakkr** [comment]
@Anne97 I can someone has already added outreachy program. Please search for once and if it is not there send a PR.

**Comment by Anne97** [comment]
@dipakkr  I checked once yesterday. Couldn't find one.

**Comment by Anne97** [comment]
@dipakkr  My bad. There's one line for the internship program. I thought of adding more details like the gsoc.md file. Let me know if it's okay and if I should do it.

**Comment by dipakkr** [comment]
> @dipakkr I checked once yesterday. Couldn't find one.

**@Anne97 it's there in SOC under 4. OPen Source Program.**

**Comment by dipakkr** [comment]
@Anne97 you can do that if you not able to understand where to add. Just make a new file and add. We will later format it in proper section.

**Comment by Contrevien** [comment]
Thank you for a splendid Hacktoberfest Contributors! :tada:
