### ISSUE TITLE
Broken link /Conferences/PyCon

### ISSUE THREAD

**Issue by Contrevien** [dipakkr/A-to-Z-Resources-for-Students#76]
First link in the conferences table (PyCon) is broken.

**Comment by CruiseDevice** [comment]
What link should be there in place of that?

**Comment by dipakkr** [comment]
@CruiseDevice link should redirect to pycon website. Prefer pycon India 2019

**Comment by dipakkr** [comment]
@CruiseDevice are you willing to work on it ?

**Comment by CruiseDevice** [comment]
@dipakkr yes

**Comment by CruiseDevice** [comment]
I couldn't find anything related to pycon india 19.
