### ISSUE TITLE
Suggestion: Organise the list of global hackathons in chronological order

### ISSUE THREAD

**Issue by chandrasd** [dipakkr/A-to-Z-Resources-for-Students#807]
It's easier to reference them if they are in chronological order or alphabetical.

**Comment by dipakkr** [comment]
@chandrasd if you can do that, you are welcome !!

**Comment by AjithPanja** [comment]
#839 Sorted the Global Hackathons in Alphabetical Order for quick look-up

**Comment by AjithPanja** [comment]
> @chandrasd if you can do that, you are welcome !!

#839 Sorted the Global Hackathons in Alphabetical Order for quick look-up

**Comment by AjithPanja** [comment]
#839 Sorted the Global Hackathons in Alphabetical Order for Quick look-up
