### ISSUE TITLE
Update Conference Section

### ISSUE THREAD

**Issue by dipakkr** [dipakkr/A-to-Z-Resources-for-Students#9]
Tasks for Conference Section : 

- [x] Update Conference Location
- [ ] Update travel reimbursment status
- [x] Update application period and deadline

**Comment by reesea** [comment]
Is this on available?

**Comment by dipakkr** [comment]
@reesea yes, you can work on it.

**Comment by reesea** [comment]
Where is the info? Like the travel info.

**Comment by dipakkr** [comment]
You have to search on the corresponding website and update. Or Just update
the application start and end time if you want.

**Comment by reesea** [comment]
Got it!
