### ISSUE TITLE
Suggestion: adding code bootcamps

### ISSUE THREAD

**Issue by bpkaur** [dipakkr/A-to-Z-Resources-for-Students#973]
Making a list of bootcamps that people can attend, some people prefer learning that way so I thought maybe it's a good idea if we can have a list for them to refer to.

**Comment by dipakkr** [comment]
@bpkaur noted !! it would be great if you can initialize this section by sending a PR.

**Comment by bpkaur** [comment]
@dipakkr Okay. I'll do it. Thank you. :)

**Comment by dipakkr** [comment]
#670 fixed

**Comment by dipakkr** [comment]
fixed !!
